### ISSUE TITLE
Incorrect plugin path 

### ISSUE THREAD

**Issue by stefanopiovesan** [plasticbox/grpc-windows#1]
A small issue: in the test_protoc.bat the plugin folder should be corrected:<br>

`set protoc_path_p=%path%\..\grpc\bin\grpc_protoc_plugins`
and change:
`%protoc_path%\protoc.exe helloworld.proto --grpc_out=%output_client_path% --plugin=protoc-gen-grpc=%protoc_path_p%\grpc_cpp_plugin.exe --proto_path=.\`<br>
`%protoc_path%\protoc.exe helloworld.proto --grpc_out=%output_server_path% --plugin=protoc-gen-grpc=%protoc_path_p%\grpc_cpp_plugin.exe --proto_path=.\`

**Comment by plasticbox** [comment]
@stefanopiovesan , @fredchyan 
Thanks ;)
