### ISSUE TITLE
grpc_clone.bat finish early on Windows 10 64-bit

### ISSUE THREAD

**Issue by iamwired** [plasticbox/grpc-windows#4]
Hi,

First, thank you for this project, as building grpc on Windows is a real pain in the butt ;)

Now my problem:
No matter what, I cannot make "grpc_clone.bat" works properly on a brand new grpc-windows directory, in an ordinary console windows on Windows 10 64-bit.

The batch process exit right after executing the "git clone -b v1.3.x https://github.com/grpc/grpc" command. The "cd grpc" command and the following ones are not executed:

```
C:\Downloads\grpc-windows>grpc_clone.bat
#### grpc clone start!
#### git clone
Cloning into 'grpc'...
remote: Counting objects: 296110, done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 296110 (delta 80), reused 91 (delta 51), pack-reused 295945
Receiving objects: 100% (296110/296110), 122.77 MiB | 2.77 MiB/s, done.
Resolving deltas: 100% (225320/225320), done.
Checking out files: 100% (9145/9145), done.

C:\Downloads\grpc-windows>
```

If I execute them manually, they work great. If I clone "grpc_clone.bat" into a new file, remove all lines until "cd grpc" and run this batch, the cloning process resume correctly and is executed til the end.

I tried to replace all end of line characters with the proper Windows shenanigan (\r\n), but to no avail.

I am lost. I don't see what causes this .bat to stop right after the "git clone ..." line.

Any idea?

P.S. Same problem with a Visual Studio 2015 "Developer Command Prompt", instead of the default console prompt.

**Comment by plasticbox** [comment]
Hi~

I'm already used WIndows 10 64-bit ;)
so run tested on Win10 RS1, RS2. unfortunately.. it's works very well in my sys.

but.. how about double quotes?
cd "grpc"
cd ".."

**Comment by iamwired** [comment]
Hello,

Thanks to [this post](https://stackoverflow.com/questions/5401229/how-do-i-execute-several-git-commands-in-a-batch-file-without-terminating-after), I managed to make "grpc_clone.bat" works on my computer.

I just inserted the "call" command in front of the git commands (lines 7 & 9).

```
...
echo #### git clone
call git clone -b v1.3.x https://github.com/grpc/grpc
cd grpc
call git submodule update --init
cd ..
...

```

Could you check if this work for you as well and then apply the fix please?
Thanks.

**Comment by plasticbox** [comment]
fixed it.
https://github.com/plasticbox/grpc-windows/commit/6b4b19f68f10f9d5ca4c653044e915364dd2fede

Thanks.
